### ISSUE TITLE
Append error message to div instead of inserting after it

### ISSUE THREAD

**Issue by javierm** [mcurry/js_validate#1]
When using server-side validation, CakePHP appends the error message to the div of the input with the error.

However, the validation plugin inserts the error message after that div, which (in some cases) breaks the style.

The following patch solves the problem:

--- a/vendors/js/jquery.validation.js
+++ b/vendors/js/jquery.validation.js
@@ -158,7 +158,7 @@
     //add the form-error class to the input
     $("#" + field).addClass("form-error")
                   .parents("div:first").addClass("error")
-                  .after('<div class="error-message">'  + message +  '</div>');
- ```
               .append('<div class="error-message">'  + message +  '</div>');
  ```
  
  };
  
  $.fn.validate.beforeFilter = function() {

**Comment by mcurry** [comment]
Fixed
