### ISSUE TITLE
Links to edit fields in the errors summary

### ISSUE THREAD

**Issue by javierm** [mcurry/js_validate#2]
It would be nice if the error messages shown in the summary (configurable with the 'messageId' option) were actual links to edit the fields. Or, at least, having some options to configure the way this summary is displayed would help making the server-side and client-side validation look the same.

Here's an example of a form with errors handled the way I mean: http://www.usability.com.au/resources/wcag2/form7.html

**Comment by mcurry** [comment]
I intentionally left these functions very basic.  You can set your own handling by redefining the functions in the apps js:
$.fn.validate.afterFilter = function(errors) { ... }

**Comment by javierm** [comment]
Sure, but the problem is, these errors are only messages. It's impossible to configure them to be links if you don't know which field they're related to.

BTW, a few days ago I noticed I fucked the API with my changes here :-(.

**Comment by mcurry** [comment]
good point.  I think it makes sense to pass more info like you had it, but keep the functions basic.

**Comment by javierm** [comment]
I agree. I overlooked the fact that the funcionality can already be overriden, and you're right by making it very basic by default.
