### ISSUE TITLE
rule minLength don't validate multiline textarea

### ISSUE THREAD

**Issue by tomao** [mcurry/js_validate#3]
When you write multiple line in a input textarea, rule "minLength" don't accept.
I solve it by this code in "validation.php" l.203 :
case 'minLength':
  return sprintf('/^.{%d,}/', $params[0]);
case 'maxLength':
  return sprintf('/^.{0,%d}/', $params[0]);

**Comment by mcurry** [comment]
Thanks,
Couldn't get your fix to work, so I did a different way.
http://github.com/mcurry/js_validate/commit/aae818d2f2ce575b2e1bcbe1abac441f59af9247
