### ISSUE TITLE
Manual Form Handling code in README not working

### ISSUE THREAD

**Issue by mikhuang** [mcurry/js_validate#4]
Good stuff. However, copying in the sample code from README leads to the opts field being empty. Additionally, I can't seem to get a response even when I use something like "$.fn.validate($("#PictureUploadForm").data("validation"), {"root":"\/","watch":[]});"

**Comment by mcurry** [comment]
What version of Cake are you using?  Do the unit tests pass (/test.php?case=models%2Fjs_validate.test.php&plugin=js_validate)?

**Comment by mcurry** [comment]
Never mind...I see it.

**Comment by mcurry** [comment]
manual validation should be better w/ latest update.
