### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LimeBlast** [mcurry/js_validate#5]
Hi, I've followed the instructions, and am getting the jQuery validation code appearing on the screen, but upon hitting submit, it doesn't trigger.

**Comment by mcurry** [comment]
Do you have a link or can you post the code you're using?

**Comment by LimeBlast** [comment]
Oh god, schoolboy error... Sorry, I've removed it from the site for the moment, but I'll try installing it again this weekend and post the code then.

**Comment by mcurry** [comment]
No response...closing
