### ISSUE TITLE
Failed test case: testUrl

### ISSUE THREAD

**Issue by ghost** [mcurry/js_validate#8]
Hello,
I have a failed test case for testUrl:

Equal expectation fails at character 1555 with [...museum|travel))(?::[1-9][0-9]{0,4})?(?:\\/?|\\/([\!\"\$&'\(\)\_\+,\-\.@_\:;\=~\\/0-9a-z]|(%[0-9a-f]{2}))_)?(?:\?([\!\"\$&'\(\)\_\+,\-\.@_\:;\=~\\/0-9a-z]|(%[0-9a-f]{2}))_)?(?:...] and [...museum|travel))(?::[1-9][0-9]{0,4})?(?:\\/?|\\/([\!\"\$&'\(\)\_\+,\-\.@_\:;\=~\\/0-9a-z\p{L}\p{N}]|(%[0-9a-f]{2}))_)?(?:\?([\!\"\$&'\(\)\*\+,\-\.@_\:;\=~\\/0-9a-z\p{L}\p{N...] at [/plugins/js_validate/tests/cases/models/js_validate.test.php line 203]
/plugins/js_validate//tests/cases/models/js_validate.test.php -> JsValidateTestCase -> testUrl

I am not sure if this affects anything.... Just reporting it in!

**Comment by mcurry** [comment]
I'm not getting this one.  What version of Cake are you using?

**Comment by netappu** [comment]
Sorry everything is working now. I was using the 1.3 branch. Not sure why it wasn't working but the master branch worked just fine.

Thanks!
