### ISSUE TITLE
Is there a way to validate without submitting?

### ISSUE THREAD

**Issue by ghost** [mcurry/js_validate#9]
Use case: using a jquery dialog box, where you manually call post via javascript. You would want to validate before you post and close the dialog box. The submit button is not output via php but through JS. The form actually never gets "submitted" in the traditional sense the fields are just grabbed and sent through post.

**Comment by netappu** [comment]
$('form').submit(); will perform a check, but it will also perform the submit... I am hoping to prevent the form from submitting even if there are no validation issues.

**Comment by netappu** [comment]
Okkk i got it check out my fork...
You should be able to: $('form').validation_check(); or whatever element(s).

I am pretty sure the: validation_elements array placed in the root of the document is a dirty technique, but I wasn't quite sure how else to do it.
